apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lj0e4dec1-nodejs
  janus-idp.io/tekton: lj0e4dec1-nodejs
  backstage.io/kubernetes-id: lj0e4dec1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lj0e4dec1-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
